[package]
name = "rust_tutorial_05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.0.1"
chrono = "0.4.15"
libp2p = "0.51.3"
